name: Quay Management
on:
  push:
    paths:
      - "ansible/**"
    branches:
      - "main"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"

# Declare default permissions as read only.
permissions: read-all

jobs:
  quay-management:
    name: "Quay Organization Management"
    if: "github.repository == 'redhat-cop/org'"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        
      - name: Run ansible-lint
        uses: ansible/ansible-lint@25f783cce3ab921f4f65e53a75e731e0420ba8f2 # v24.9.0

      - name: Install Dependencies
        run: ansible-galaxy install -r ansible/requirements.yml -p $HOME/roles

      - name: Manage Quay Repository
        if: github.event_name == 'push' || github.event_name == 'schedule'
        env:
          ANSIBLE_ROLES_PATH: '$HOME/roles/infra-ansible/roles/scm'
        run: ansible-playbook -i ansible/inventory ansible/playbooks/quay_management.yml ${{secrets.ANSIBLE_EXTRA_VARS}}
